// frontend/src/pages/ProductDetail.jsx
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import {
  Container,
  Grid,
  Typography,
  Button,
  Card,
  CardMedia,
  Box,
  Chip,
  Rating,
  Divider,
  IconButton,
  TextField,
  Tabs,
  Tab,
  Alert
} from '@mui/material';
import {
  ShoppingCart,
  Favorite,
  FavoriteBorder,
  Share,
  Add,
  Remove
} from '@mui/icons-material';
import { useQuery, useMutation, useQueryClient } from 'react-query';
import toast from 'react-hot-toast';
import api, { cartAPI } from '../services/api';
import { useAuthStore } from '../stores/authStore';

function TabPanel({ children, value, index, ...other }) {
  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`product-tabpanel-${index}`}
      aria-labelledby={`product-tab-${index}`}
      {...other}
    >
      {value === index && (
        <Box sx={{ p: 3 }}>
          {children}
        </Box>
      )}
    </div>
  );
}

export default function ProductDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { user } = useAuthStore();
  const queryClient = useQueryClient();

  const [selectedImage, setSelectedImage] = useState(0);
  const [selectedVariant, setSelectedVariant] = useState(null);
  const [quantity, setQuantity] = useState(1);
  const [tabValue, setTabValue] = useState(0);
  const [reviewText, setReviewText] = useState('');
  const [reviewRating, setReviewRating] = useState(5);
  const [isWishlisted, setIsWishlisted] = useState(false);

  // 獲取產品詳情
  const { data: product, isLoading, error } = useQuery(
    ['product', id],
    () => api.get(`/products/${id}`).then(res => res.data),
    {
      enabled: !!id,
      onSuccess: (data) => {
        if (data.variants && data.variants.length > 0) {
          setSelectedVariant(data.variants[0]);
        }
      }
    }
  );

  // 獲取產品評論
  const { data: reviews } = useQuery(
    ['product-reviews', id],
    () => api.get(`/products/${id}/reviews`).then(res => res.data),
    { enabled: !!id }
  );

  // 添加到購物車
  const addToCartMutation = useMutation(
    async () => {
      if (!user?.id) {
        throw new Error('請先登入');
      }
      return await cartAPI.addToCart(user.id, {
        productId: product.id,
        quantity
      });
    },
    {
      onSuccess: () => {
        toast.success('已添加到購物車');
      },
      onError: (error) => {
        toast.error(error.response?.data?.message || '添加失敗');
      }
    }
  );

  // 添加評論
  const addReviewMutation = useMutation(
    (data) => api.post(`/products/${id}/reviews`, data),
    {
      onSuccess: () => {
        toast.success('評論提交成功');
        setReviewText('');
        setReviewRating(5);
        queryClient.invalidateQueries(['product-reviews', id]);
      },
      onError: (error) => {
        toast.error(error.response?.data?.message || '評論提交失敗');
      }
    }
  );

  // 加入/移除願望清單
  const toggleWishlistMutation = useMutation(
    () => {
      return isWishlisted
        ? api.delete(`/wishlist/items/${id}`)
        : api.post('/wishlist/items', null, { params: { productId: id } });
    },
    {
      onSuccess: () => {
        setIsWishlisted(!isWishlisted);
        toast.success(isWishlisted ? '已從願望清單移除' : '已加入願望清單');
      }
    }
  );

  const handleAddToCart = () => {
    if (!user) {
      navigate('/login');
      return;
    }

    addToCartMutation.mutate({
      productId: product.id,
      variantId: selectedVariant?.id,
      quantity
    });
  };

  const handleSubmitReview = () => {
    if (!user) {
      navigate('/login');
      return;
    }

    if (!reviewText.trim()) {
      toast.error('請輸入評論內容');
      return;
    }

    addReviewMutation.mutate({
      rating: reviewRating,
      comment: reviewText
    });
  };

  const getCurrentPrice = () => {
    return selectedVariant ? selectedVariant.price : product?.price || 0;
  };

  const getStockQuantity = () => {
    return selectedVariant ? selectedVariant.stock : product?.stock || 0;
  };

  if (isLoading) {
    return (
      <Container sx={{ py: 4 }}>
        <Typography>載入中...</Typography>
      </Container>
    );
  }

  if (error || !product) {
    return (
      <Container sx={{ py: 4 }}>
        <Alert severity="error">
          找不到該產品或載入失敗
        </Alert>
      </Container>
    );
  }

  return (
    <Container maxWidth="lg" sx={{ py: 4 }}>
      <Grid container spacing={4}>
        {/* 產品圖片 */}
        <Grid item xs={12} md={6}>
          <Card>
            <CardMedia
              component="img"
              height="400"
              image={product.images?.[selectedImage]?.url || '/api/placeholder/400/400'}
              alt={product.name}
              sx={{ objectFit: 'contain' }}
            />
          </Card>

          {product.images && product.images.length > 1 && (
            <Box sx={{ display: 'flex', gap: 1, mt: 2, overflow: 'auto' }}>
              {product.images.map((image, index) => (
                <Card
                  key={index}
                  sx={{
                    minWidth: 80,
                    cursor: 'pointer',
                    border: selectedImage === index ? '2px solid primary.main' : 'none'
                  }}
                  onClick={() => setSelectedImage(index)}
                >
                  <CardMedia
                    component="img"
                    height="80"
                    image={image.url}
                    alt={`${product.name} ${index + 1}`}
                  />
                </Card>
              ))}
            </Box>
          )}
        </Grid>

        {/* 產品信息 */}
        <Grid item xs={12} md={6}>
          <Typography variant="h4" gutterBottom>
            {product.name}
          </Typography>

          <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, mb: 2 }}>
            <Rating value={product.averageRating || 0} readOnly precision={0.1} />
            <Typography variant="body2" color="text.secondary">
              ({product.reviewCount || 0} 評論)
            </Typography>
          </Box>

          <Typography variant="h5" color="primary" gutterBottom>
            NT$ {getCurrentPrice()}
          </Typography>

          <Typography variant="body1" paragraph>
            {product.description}
          </Typography>

          {/* 產品變體選擇 */}
          {product.variants && product.variants.length > 0 && (
            <Box sx={{ mb: 3 }}>
              <Typography variant="h6" gutterBottom>
                選擇規格
              </Typography>
              <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap' }}>
                {product.variants.map((variant) => (
                  <Chip
                    key={variant.id}
                    label={`${variant.name} - NT$ ${variant.price}`}
                    variant={selectedVariant?.id === variant.id ? 'filled' : 'outlined'}
                    color={selectedVariant?.id === variant.id ? 'primary' : 'default'}
                    onClick={() => setSelectedVariant(variant)}
                  />
                ))}
              </Box>
            </Box>
          )}

          {/* 標籤 */}
          {product.tags && product.tags.length > 0 && (
            <Box sx={{ mb: 3 }}>
              <Typography variant="h6" gutterBottom>
                標籤
              </Typography>
              <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap' }}>
                {product.tags.map((tag) => (
                  <Chip key={tag.id} label={tag.name} size="small" />
                ))}
              </Box>
            </Box>
          )}

          {/* 數量選擇 */}
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, mb: 3 }}>
            <Typography variant="h6">數量：</Typography>
            <Box sx={{ display: 'flex', alignItems: 'center' }}>
              <IconButton
                onClick={() => setQuantity(Math.max(1, quantity - 1))}
                disabled={quantity <= 1}
              >
                <Remove />
              </IconButton>
              <Typography sx={{ mx: 2, minWidth: 40, textAlign: 'center' }}>
                {quantity}
              </Typography>
              <IconButton
                onClick={() => setQuantity(Math.min(getStockQuantity(), quantity + 1))}
                disabled={quantity >= getStockQuantity()}
              >
                <Add />
              </IconButton>
            </Box>
            <Typography variant="body2" color="text.secondary">
              庫存：{getStockQuantity()}
            </Typography>
          </Box>

          {/* 操作按鈕 */}
          <Box sx={{ display: 'flex', gap: 2, mb: 3 }}>
            <Button
              variant="contained"
              size="large"
              startIcon={<ShoppingCart />}
              onClick={handleAddToCart}
              disabled={getStockQuantity() === 0 || addToCartMutation.isLoading}
              sx={{ flex: 1 }}
            >
              {getStockQuantity() === 0 ? '缺貨' : '加入購物車'}
            </Button>

            <IconButton
              onClick={() => toggleWishlistMutation.mutate()}
              color={isWishlisted ? 'error' : 'default'}
            >
              {isWishlisted ? <Favorite /> : <FavoriteBorder />}
            </IconButton>

            <IconButton>
              <Share />
            </IconButton>
          </Box>
        </Grid>
      </Grid>

      {/* 詳細信息標籤頁 */}
      <Box sx={{ mt: 4 }}>
        <Tabs value={tabValue} onChange={(e, newValue) => setTabValue(newValue)}>
          <Tab label="產品詳情" />
          <Tab label={`評論 (${reviews?.length || 0})`} />
          <Tab label="規格" />
        </Tabs>

        <TabPanel value={tabValue} index={0}>
          <Typography variant="body1" style={{ whiteSpace: 'pre-line' }}>
            {product.longDescription || product.description}
          </Typography>
        </TabPanel>

        <TabPanel value={tabValue} index={1}>
          {/* 寫評論 */}
          {user && (
            <Card sx={{ p: 3, mb: 3 }}>
              <Typography variant="h6" gutterBottom>
                寫評論
              </Typography>
              <Box sx={{ mb: 2 }}>
                <Typography component="legend">評分</Typography>
                <Rating
                  value={reviewRating}
                  onChange={(event, newValue) => setReviewRating(newValue)}
                />
              </Box>
              <TextField
                fullWidth
                multiline
                rows={4}
                value={reviewText}
                onChange={(e) => setReviewText(e.target.value)}
                placeholder="分享您的使用心得..."
                sx={{ mb: 2 }}
              />
              <Button
                variant="contained"
                onClick={handleSubmitReview}
                disabled={addReviewMutation.isLoading}
              >
                提交評論
              </Button>
            </Card>
          )}

          {/* 評論列表 */}
          {reviews?.map((review) => (
            <Card key={review.id} sx={{ p: 3, mb: 2 }}>
              <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 2 }}>
                <Typography variant="h6">{review.user.name}</Typography>
                <Typography variant="body2" color="text.secondary">
                  {new Date(review.createdAt).toLocaleDateString()}
                </Typography>
              </Box>
              <Rating value={review.rating} readOnly size="small" sx={{ mb: 1 }} />
              <Typography variant="body1">{review.comment}</Typography>
            </Card>
          ))}

          {!reviews || reviews.length === 0 && (
            <Typography color="text.secondary">
              暫無評論
            </Typography>
          )}
        </TabPanel>

        <TabPanel value={tabValue} index={2}>
          <Grid container spacing={2}>
            <Grid item xs={6}>
              <Typography variant="body2" color="text.secondary">品牌</Typography>
              <Typography variant="body1">{product.brand || '未指定'}</Typography>
            </Grid>
            <Grid item xs={6}>
              <Typography variant="body2" color="text.secondary">型號</Typography>
              <Typography variant="body1">{product.model || '未指定'}</Typography>
            </Grid>
            <Grid item xs={6}>
              <Typography variant="body2" color="text.secondary">重量</Typography>
              <Typography variant="body1">{product.weight || '未指定'}</Typography>
            </Grid>
            <Grid item xs={6}>
              <Typography variant="body2" color="text.secondary">尺寸</Typography>
              <Typography variant="body1">{product.dimensions || '未指定'}</Typography>
            </Grid>
          </Grid>
        </TabPanel>
      </Box>
    </Container>
  );
}

// frontend/src/pages/ProductDetail.vue
<template>
  <v-container class="py-4" style="max-width: 1200px">
    <!-- 載入中 -->
    <div v-if="loading" class="d-flex justify-center pa-8">
      <v-progress-circular indeterminate color="primary" size="64" />
    </div>

    <!-- 錯誤 -->
    <v-alert v-else-if="error" type="error" class="ma-4">找不到該產品或載入失敗</v-alert>

    <template v-else-if="product">
      <v-row>
        <!-- 商品圖片 -->
        <v-col cols="12" md="6">
          <v-card>
            <v-img
              :src="product.images?.[selectedImage]?.url || '/api/placeholder/600/400'"
              height="400"
              cover
            />
          </v-card>
          <div v-if="product.images && product.images.length > 1" class="d-flex ga-2 mt-2 overflow-auto">
            <v-card
              v-for="(img, idx) in product.images"
              :key="idx"
              :class="['flex-shrink-0', selectedImage === idx ? 'border-primary border-md' : '']"
              width="80"
              @click="selectedImage = idx"
              style="cursor: pointer"
            >
              <v-img :src="img.url" height="80" cover />
            </v-card>
          </div>
        </v-col>

        <!-- 商品資訊 -->
        <v-col cols="12" md="6">
          <h1 class="text-h4 font-weight-bold mb-2">{{ product.name }}</h1>

          <div class="d-flex align-center ga-2 mb-4">
            <v-rating
              :model-value="product.averageRating || 0"
              readonly
              half-increments
              density="compact"
              color="amber"
            />
            <span class="text-body-2 text-medium-emphasis">({{ product.reviewCount || 0 }} 評論)</span>
          </div>

          <p class="text-h5 text-primary font-weight-bold mb-3">NT$ {{ currentPrice }}</p>

          <p class="text-body-1 mb-4">{{ product.description }}</p>

          <!-- 規格選擇 -->
          <div v-if="product.variants && product.variants.length > 0" class="mb-4">
            <p class="text-subtitle-1 font-weight-medium mb-2">選擇規格</p>
            <div class="d-flex flex-wrap ga-2">
              <v-chip
                v-for="variant in product.variants"
                :key="variant.id"
                :color="selectedVariant?.id === variant.id ? 'primary' : undefined"
                :variant="selectedVariant?.id === variant.id ? 'elevated' : 'outlined'"
                @click="selectedVariant = variant"
              >
                {{ variant.name }} - NT$ {{ variant.price }}
              </v-chip>
            </div>
          </div>

          <!-- 標籤 -->
          <div v-if="product.tags && product.tags.length > 0" class="mb-4">
            <div class="d-flex flex-wrap ga-1">
              <v-chip v-for="tag in product.tags" :key="tag.id" size="small" variant="outlined">
                {{ tag.name }}
              </v-chip>
            </div>
          </div>

          <!-- 數量選擇 -->
          <div class="d-flex align-center ga-3 mb-4">
            <span class="text-subtitle-1 font-weight-medium">數量：</span>
            <div class="d-flex align-center">
              <v-btn icon size="small" variant="text" :disabled="quantity <= 1" @click="quantity--">
                <v-icon>mdi-minus</v-icon>
              </v-btn>
              <span class="mx-3 text-subtitle-1" style="min-width: 32px; text-align: center">{{ quantity }}</span>
              <v-btn icon size="small" variant="text" :disabled="quantity >= stockQty" @click="quantity++">
                <v-icon>mdi-plus</v-icon>
              </v-btn>
            </div>
            <span class="text-body-2 text-medium-emphasis">庫存：{{ stockQty }}</span>
          </div>

          <!-- 操作按鈕 -->
          <div class="d-flex ga-2">
            <v-btn
              color="primary"
              size="large"
              prepend-icon="mdi-cart"
              :disabled="stockQty === 0 || addingToCart"
              :loading="addingToCart"
              class="flex-grow-1"
              @click="handleAddToCart"
            >
              {{ stockQty === 0 ? '缺貨' : '加入購物車' }}
            </v-btn>
            <v-btn
              :icon="true"
              :color="isWishlisted ? 'error' : undefined"
              variant="outlined"
              @click="toggleWishlist"
            >
              <v-icon>{{ isWishlisted ? 'mdi-heart' : 'mdi-heart-outline' }}</v-icon>
            </v-btn>
          </div>
        </v-col>
      </v-row>

      <!-- 標籤頁 -->
      <v-card class="mt-6">
        <v-tabs v-model="activeTab" color="primary">
          <v-tab value="desc">產品詳情</v-tab>
          <v-tab value="reviews">評論 ({{ reviews.length }})</v-tab>
          <v-tab value="specs">規格</v-tab>
        </v-tabs>

        <v-card-text>
          <v-tabs-window v-model="activeTab">
            <!-- 描述 -->
            <v-tabs-window-item value="desc">
              <p style="white-space: pre-line">{{ product.longDescription || product.description }}</p>
            </v-tabs-window-item>

            <!-- 評論 -->
            <v-tabs-window-item value="reviews">
              <!-- 寫評論 (登入後顯示) -->
              <v-card v-if="isAuthenticated" variant="outlined" class="mb-4 pa-3">
                <p class="text-subtitle-1 font-weight-medium mb-2">寫評論</p>
                <p class="text-body-2 mb-1">評分</p>
                <v-rating v-model="reviewRating" color="amber" class="mb-3" />
                <v-textarea
                  v-model="reviewText"
                  label="分享您的使用心得..."
                  variant="outlined"
                  rows="3"
                  class="mb-3"
                />
                <v-btn color="primary" :loading="submittingReview" @click="handleSubmitReview">
                  提交評論
                </v-btn>
              </v-card>

              <!-- 評論列表 -->
              <v-card
                v-for="review in reviews"
                :key="review.id"
                variant="outlined"
                class="mb-3 pa-3"
              >
                <div class="d-flex justify-space-between mb-1">
                  <span class="font-weight-medium">{{ review.user?.name || review.user?.username }}</span>
                  <span class="text-body-2 text-medium-emphasis">{{ formatDate(review.createdAt) }}</span>
                </div>
                <v-rating :model-value="review.rating" readonly density="compact" color="amber" size="small" class="mb-1" />
                <p class="text-body-1">{{ review.comment }}</p>
              </v-card>

              <p v-if="reviews.length === 0" class="text-medium-emphasis">暫無評論</p>
            </v-tabs-window-item>

            <!-- 規格 -->
            <v-tabs-window-item value="specs">
              <v-row>
                <v-col cols="6">
                  <p class="text-body-2 text-medium-emphasis">品牌</p>
                  <p>{{ product.brand || '未指定' }}</p>
                </v-col>
                <v-col cols="6">
                  <p class="text-body-2 text-medium-emphasis">型號</p>
                  <p>{{ product.model || '未指定' }}</p>
                </v-col>
                <v-col cols="6">
                  <p class="text-body-2 text-medium-emphasis">重量</p>
                  <p>{{ product.weight || '未指定' }}</p>
                </v-col>
                <v-col cols="6">
                  <p class="text-body-2 text-medium-emphasis">尺寸</p>
                  <p>{{ product.dimensions || '未指定' }}</p>
                </v-col>
              </v-row>
            </v-tabs-window-item>
          </v-tabs-window>
        </v-card-text>
      </v-card>
    </template>
  </v-container>
</template>

<script setup>
import { ref, computed, onMounted, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useToast } from 'vue-toastification'
import { useAuthStore } from '../stores/authStore.js'
import api, { cartAPI, wishlistAPI } from '../services/api.js'

const route = useRoute()
const router = useRouter()
const toast = useToast()
const authStore = useAuthStore()
const isAuthenticated = computed(() => authStore.isAuthenticated)

const product = ref(null)
const loading = ref(false)
const error = ref(false)
const reviews = ref([])
const selectedImage = ref(0)
const selectedVariant = ref(null)
const quantity = ref(1)
const activeTab = ref('desc')
const reviewText = ref('')
const reviewRating = ref(5)
const isWishlisted = ref(false)
const addingToCart = ref(false)
const submittingReview = ref(false)

const currentPrice = computed(() =>
  selectedVariant.value ? selectedVariant.value.price : product.value?.price || 0
)
const stockQty = computed(() =>
  selectedVariant.value ? selectedVariant.value.stock : product.value?.stock || 0
)

function formatDate(d) {
  return d ? new Date(d).toLocaleDateString('zh-TW') : ''
}

async function loadProduct() {
  loading.value = true
  error.value = false
  try {
    const res = await api.get(`/products/${route.params.id}`)
    product.value = res.data
    if (res.data.variants?.length > 0) selectedVariant.value = res.data.variants[0]
  } catch {
    error.value = true
  } finally {
    loading.value = false
  }
}

async function loadWishlistStatus() {
  if (!isAuthenticated.value) return
  isWishlisted.value = false
  try {
    const response = await wishlistAPI.getWishlist()
    const items = response.data?.items ?? []
    const productId = Number(route.params.id)
    isWishlisted.value = items.some(item => item.productId === productId)
  } catch {}
}

async function loadReviews() {
  try {
    const res = await api.get(`/products/${route.params.id}/reviews`)
    reviews.value = Array.isArray(res.data) ? res.data : res.data?.data || []
  } catch {}
}

async function handleAddToCart() {
  if (!isAuthenticated.value) { router.push('/login'); return }
  addingToCart.value = true
  try {
    await cartAPI.addToCart(authStore.user.id, {
      productId: product.value.id,
      variantId: selectedVariant.value?.id,
      quantity: quantity.value,
    })
    toast.success('已添加到購物車')
  } catch (err) {
    toast.error(err.response?.data?.message || '添加失敗')
  } finally {
    addingToCart.value = false
  }
}

async function toggleWishlist() {
  if (!isAuthenticated.value) { router.push('/login'); return }
  try {
    if (isWishlisted.value) {
      await api.delete(`/wishlist/items/${route.params.id}`)
      toast.success('已從願望清單移除')
    } else {
      await api.post('/wishlist/items', null, { params: { productId: route.params.id } })
      toast.success('已加入願望清單')
    }
    isWishlisted.value = !isWishlisted.value
  } catch {}
}

async function handleSubmitReview() {
  if (!reviewText.value.trim()) { toast.error('請輸入評論內容'); return }
  submittingReview.value = true
  try {
    await api.post(`/products/${route.params.id}/reviews`, {
      rating: reviewRating.value,
      comment: reviewText.value,
    })
    toast.success('評論提交成功')
    reviewText.value = ''
    reviewRating.value = 5
    await loadReviews()
  } catch (err) {
    toast.error(err.response?.data?.message || '評論提交失敗')
  } finally {
    submittingReview.value = false
  }
}

onMounted(() => {
  loadProduct()
  loadReviews()
  loadWishlistStatus()
})

watch(() => route.params.id, () => {
  loadProduct()
  loadReviews()
  loadWishlistStatus()
})
</script>
