// frontend/src/pages/Shop.jsx
﻿import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import { ShoppingCart, MessageCircle, LogOut, User, Search, Trash2, Menu, X, Filter, Bot, Heart } from 'lucide-react';

import { productAPI, cartAPI, chatAPI, wishlistAPI } from '../services/api';
import { useAuthStore } from '../stores/authStore';
import { cartEvents } from '../utils/cartEvents';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
  DialogClose,
} from '@/components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Label } from '@/components/ui/label';

function Shop() {
  const { user, logout } = useAuthStore();
  const navigate = useNavigate();
  const [products, setProducts] = useState([]);
  const [cart, setCart] = useState(null);
  const [cartItems, setCartItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('all');
  const [categories, setCategories] = useState([]);
  const [unreadCount, setUnreadCount] = useState(0); 
  const [showMobileCart, setShowMobileCart] = useState(false); 
  const [showMobileFilter, setShowMobileFilter] = useState(false);
  const [openClearCartDialog, setOpenClearCartDialog] = useState(false);
  const [wishlistedIds, setWishlistedIds] = useState(new Set());

  useEffect(() => {
    loadProducts();
    loadCart();
    loadUnreadCount();
    loadWishlist();
    const interval = setInterval(loadUnreadCount, 10000);
    return () => clearInterval(interval);
  }, []);

  useEffect(() => {
    if (cart) {
      loadCartItems();
    }
  }, [cart]);

  const loadProducts = async () => {
    try {
      const response = await productAPI.getProducts();
      const productsData = response.data?.data || response.data || [];
      setProducts(Array.isArray(productsData) ? productsData : []);
      const uniqueCategories = [...new Set(productsData.map(p => p.category).filter(c => c))];
      setCategories(uniqueCategories);
      setLoading(false);
    } catch (error) {
      console.error('載入商品失敗:', error);
      setProducts([]);
      setLoading(false);
    }
  };

  const loadCart = async () => {
    if (!user?.id) return;
    try {
      const response = await cartAPI.getCart(user.id);
      setCart(response.data?.data || response.data);
    } catch (error) {
      console.error('載入購物車失敗:', error);
    }
  };

  const loadCartItems = async () => {
    if (!user?.id) return;
    try {
      const response = await cartAPI.getCart(user.id);
      const cartData = response.data?.data || response.data;
      setCartItems(cartData?.items || []);
      setCart(cartData); 
    } catch (error) {
      console.error('載入購物車項目失敗:', error);
    }
  };

  const addToCart = async (productId) => {
    if (!user?.id) {
      toast.error('請先登入');
      return;
    }
    try {
      await cartAPI.addToCart(user.id, { productId, quantity: 1 });
      await loadCartItems();
      cartEvents.notify();
      toast.success('已加入購物車');
    } catch (error) {
      toast.error(error.response?.data?.error || '加入購物車失敗');
    }
  };

  const updateCartItemQuantity = async (itemId, quantity) => {
    if (!user?.id) return;
    if (quantity < 1) {
      await removeFromCart(itemId);
      return;
    }
    try {
      await cartAPI.updateCartItem(user.id, itemId, quantity);
      await loadCartItems();
      cartEvents.notify();
    } catch (error) {
      toast.error(error.response?.data?.error || '更新失敗');
    }
  };

  const removeFromCart = async (itemId) => {
    if (!user?.id) return;
    try {
      await cartAPI.removeFromCart(user.id, itemId);
      await loadCartItems();
      cartEvents.notify();
    } catch (error) {
      console.error('移除失敗:', error);
    }
  };

  const clearCart = async () => {
    if (!user?.id) return;
    setOpenClearCartDialog(false);
    try {
      await cartAPI.clearCart(user.id);
      await loadCartItems();
      toast.success('購物車已清空');
    } catch (error) {
      toast.error('清空購物車失敗');
    }
  };

  const loadUnreadCount = async () => {
    if (!user?.id) return;
    try {
      const response = await chatAPI.getUnreadCount(user.id);
      setUnreadCount(response.data?.unreadCount || response.data?.data?.unreadCount || 0);
    } catch (error) { console.error(error); }
  };

  const loadWishlist = async () => {
    if (!user?.id) return;
    try {
      const response = await wishlistAPI.getWishlist();
      const items = response.data?.items ?? response.data ?? [];
      const ids = new Set(items.map(item => item.productId ?? item.product?.id));
      setWishlistedIds(ids);
    } catch (error) {
      // 未登入或其他錯誤，不影響頁面
    }
  };

  const toggleWishlist = async (productId) => {
    if (!user?.id) {
      toast.error('請先登入');
      return;
    }
    try {
      if (wishlistedIds.has(productId)) {
        await wishlistAPI.removeFromWishlist(productId);
        setWishlistedIds(prev => { const next = new Set(prev); next.delete(productId); return next; });
        toast.success('已從願望清單移除');
      } else {
        await wishlistAPI.addToWishlist(productId);
        setWishlistedIds(prev => new Set(prev).add(productId));
        toast.success('已加入願望清單');
      }
    } catch (error) {
      toast.error(error.response?.data?.message || '操作失敗');
    }
  };

  const goToCheckout = () => {
    if (cartItems.length === 0) {
      toast.error('購物車是空的!');
      return;
    }
    navigate('/checkout');
  };

  const filteredProducts = Array.isArray(products) ? products.filter(product => {
    const matchesSearch = product.name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      (product.description || '').toLowerCase().includes(searchTerm.toLowerCase());
    const matchesCategory = selectedCategory === 'all' || !selectedCategory || product.category === selectedCategory;
    return matchesSearch && matchesCategory && product.active;
  }) : [];

  const cartTotal = cart?.total || cartItems.reduce((sum, item) => {
    const itemTotal = item.subtotal || (parseFloat(item.price || 0) * (item.quantity || 0));
    return sum + itemTotal;
  }, 0);
  const cartCount = cartItems.reduce((sum, item) => sum + (item.quantity || 0), 0);

  if (loading) return <div className="flex h-screen items-center justify-center">載入中...</div>;

  return (
    <div className="flex min-h-screen flex-col bg-background">
      {/* Navigation */}
      <header className="sticky top-0 z-40 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container flex h-16 items-center px-4">
          <div className="flex flex-1 items-center justify-between space-x-2 md:justify-end">
             <div className="w-full flex-1 md:w-auto md:flex-none">
                {/* Mobile Search placeholder or hidden */}
             </div>
             <nav className="flex items-center space-x-2">
                {/* <Button variant="ghost" size="icon" onClick={() => navigate('/ai')} title="AI 助手" className="relative">*/}{/* TODO: AI 功能暫時停用 */}
                {/*   <Bot className="h-5 w-5" />*/}
                {/* </Button>*/}
                <Button variant="ghost" size="icon" onClick={() => navigate('/chat')} className="relative">
                  <MessageCircle className="h-5 w-5" />
                  {unreadCount > 0 && (
                    <Badge variant="destructive" className="absolute -right-1 -top-1 px-1 min-w-[1.25rem] h-5 justify-center">
                      {unreadCount}
                    </Badge>
                  )}
                </Button>
                <Button variant="ghost" size="icon" onClick={() => setShowMobileCart(true)} className="md:hidden relative">
                   <ShoppingCart className="h-5 w-5" />
                   {cartCount > 0 && (
                    <Badge className="absolute -right-1 -top-1 px-1 min-w-[1.25rem] h-5 justify-center">
                      {cartCount}
                    </Badge>
                  )}
                </Button>
                <div className="hidden md:flex items-center gap-2">
                   <span className="text-sm font-medium"> {user?.name || user?.username}</span>
                   <Button variant="outline" size="sm" onClick={() => { logout(); navigate('/login'); }}>
                     登出
                   </Button>
                </div>
             </nav>
          </div>
        </div>
      </header>

      <div className="container flex-1 items-start md:grid md:grid-cols-[240px_1fr] md:gap-6 md:px-4 md:py-6">
        {/* Sidebar */}
        <aside className="fixed top-14 z-30 -ml-2 hidden h-[calc(100vh-3.5rem)] w-full shrink-0 overflow-y-auto border-r md:sticky md:block">
          <div className="py-6 pr-6 lg:py-8">
            <h3 className="mb-4 text-lg font-semibold">篩選與搜尋</h3>
            <div className="space-y-4">
               <div className="space-y-2">
                 <Label>搜尋商品</Label>
                 <div className="relative">
                   <Search className="absolute left-2 top-2.5 h-4 w-4 text-muted-foreground" />
                   <Input 
                     placeholder="輸入關鍵字..." 
                     className="pl-8"
                     value={searchTerm}
                     onChange={(e) => setSearchTerm(e.target.value)}
                   />
                 </div>
               </div>
               <div className="space-y-2">
                 <Label>商品分類</Label>
                 <Select value={selectedCategory} onValueChange={setSelectedCategory}>
                    <SelectTrigger>
                      <SelectValue placeholder="選擇分類" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">全部商品</SelectItem>
                      {categories.map(cat => (
                        <SelectItem key={cat} value={cat}>{cat}</SelectItem>
                      ))}
                    </SelectContent>
                 </Select>
               </div>
            </div>

            <div className="mt-8 border-t pt-6">
               <h3 className="mb-4 text-lg font-semibold flex items-center gap-2">
                 <ShoppingCart className="h-5 w-5" /> 購物車
               </h3>
               <div className="space-y-4">
                  <div className="flex justify-between text-sm">
                    <span>商品數量:</span>
                    <span className="font-medium">{cartCount}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span>總金額:</span>
                    <span className="font-medium text-primary"></span>
                  </div>
                  
                  {cartItems.length > 0 ? (
                    <div className="space-y-3">
                      <div className="max-h-[300px] overflow-y-auto space-y-2 pr-2">
                        {cartItems.map(item => (
                          <div key={item.id} className="flex justify-between items-start text-sm border-b pb-2">
                             <div className="flex-1">
                               <p className="font-medium truncate">{item.productName || item.product?.name}</p>
                               <p className="text-muted-foreground text-xs"> x {item.quantity}</p>
                             </div>
                             <div className="flex items-center gap-1">
                               <Button variant="ghost" size="icon" className="h-6 w-6" onClick={() => updateCartItemQuantity(item.id, item.quantity - 1)}>-</Button>
                               <span className="w-4 text-center">{item.quantity}</span>
                               <Button variant="ghost" size="icon" className="h-6 w-6" onClick={() => updateCartItemQuantity(item.id, item.quantity + 1)}>+</Button>
                               <Button variant="ghost" size="icon" className="h-6 w-6 text-destructive" onClick={() => removeFromCart(item.id)}>
                                 <Trash2 className="h-3 w-3" />
                               </Button>
                             </div>
                          </div>
                        ))}
                      </div>
                      <div className="grid gap-2">
                        <Button className="w-full" onClick={goToCheckout}>結帳</Button>
                        <Button variant="outline" className="w-full" onClick={() => setOpenClearCartDialog(true)}>清空</Button>
                      </div>
                    </div>
                  ) : (
                    <div className="text-center py-6 text-muted-foreground text-sm">
                      購物車是空的
                    </div>
                  )}
               </div>
            </div>
          </div>
        </aside>

        {/* Main Content */}
        <main className="py-6">
           <div className="flex items-center gap-2 mb-6 md:hidden">
             <Button variant="outline" className="w-full" onClick={() => setShowMobileFilter(true)}>
               <Filter className="mr-2 h-4 w-4" /> 篩選與搜尋
             </Button>
           </div>
           <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
             {filteredProducts.length === 0 ? (
               <div className="col-span-full text-center py-12 text-muted-foreground">
                 沒有找到符合的商品
               </div>
             ) : (
               filteredProducts.map(product => (
                 <Card key={product.id} className="overflow-hidden flex flex-col h-full">
                   <div className="aspect-square bg-muted flex items-center justify-center relative">
                     {product.imageUrl ? (
                       <img src={product.imageUrl} alt={product.name} className="object-cover w-full h-full" />
                     ) : (
                       <span className="text-4xl"></span>
                     )}
                     {product.stock === 0 && (
                       <div className="absolute inset-0 bg-background/80 flex items-center justify-center">
                         <Badge variant="secondary" className="text-lg">缺貨</Badge>
                       </div>
                     )}
                   </div>
                   <CardHeader className="p-4">
                     <div className="flex justify-between items-start gap-2">
                       <CardTitle className="text-lg line-clamp-1">{product.name}</CardTitle>
                       {product.category && <Badge variant="outline" className="shrink-0">{product.category}</Badge>}
                     </div>
                   </CardHeader>
                   <CardContent className="p-4 pt-0 flex-1">
                     <p className="text-sm text-muted-foreground line-clamp-2 min-h-[2.5rem]">
                       {product.description}
                     </p>
                     <div className="mt-4 flex items-baseline justify-between">
                       <span className="text-xl font-bold"></span>
                       <span className="text-xs text-muted-foreground">庫存: {product.stock}</span>
                     </div>
                   </CardContent>
                   <CardFooter className="p-4 pt-0 flex gap-2">
                     <Button 
                       className="flex-1" 
                       disabled={product.stock === 0}
                       onClick={() => addToCart(product.id)}
                     >
                       {product.stock === 0 ? '缺貨' : '加入購物車'}
                     </Button>
                     <Button
                       variant="outline"
                       size="icon"
                       onClick={() => toggleWishlist(product.id)}
                       title={wishlistedIds.has(product.id) ? '從願望清單移除' : '加入願望清單'}
                     >
                       <Heart
                         className="h-4 w-4"
                         fill={wishlistedIds.has(product.id) ? 'currentColor' : 'none'}
                         color={wishlistedIds.has(product.id) ? '#ef4444' : 'currentColor'}
                       />
                     </Button>
                   </CardFooter>
                 </Card>
               ))
             )}
           </div>
        </main>
      </div>

      {/* Mobile Filter Overlay */}
      {showMobileFilter && (
        <div className="fixed inset-0 z-50 bg-background/80 backdrop-blur-sm md:hidden">
          <div className="fixed inset-y-0 left-0 z-50 h-full w-full border-r bg-background p-6 shadow-lg sm:max-w-sm">
             <div className="flex items-center justify-between mb-6">
               <h3 className="text-lg font-semibold">篩選與搜尋</h3>
               <Button variant="ghost" size="icon" onClick={() => setShowMobileFilter(false)}>
                 <X className="h-4 w-4" />
               </Button>
             </div>
             <div className="space-y-4">
               <div className="space-y-2">
                 <Label>搜尋商品</Label>
                 <div className="relative">
                   <Search className="absolute left-2 top-2.5 h-4 w-4 text-muted-foreground" />
                   <Input 
                     placeholder="輸入關鍵字..." 
                     className="pl-8"
                     value={searchTerm}
                     onChange={(e) => setSearchTerm(e.target.value)}
                   />
                 </div>
               </div>
               <div className="space-y-2">
                 <Label>商品分類</Label>
                 <Select value={selectedCategory} onValueChange={setSelectedCategory}>
                    <SelectTrigger>
                      <SelectValue placeholder="選擇分類" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">全部商品</SelectItem>
                      {categories.map(cat => (
                        <SelectItem key={cat} value={cat}>{cat}</SelectItem>
                      ))}
                    </SelectContent>
                 </Select>
               </div>
               <div className="pt-4">
                  <Button className="w-full" onClick={() => setShowMobileFilter(false)}>
                    確認
                  </Button>
               </div>
            </div>
          </div>
        </div>
      )}

      {/* Mobile Cart Overlay (Optional simplified version) */}
      {showMobileCart && (
        <div className="fixed inset-0 z-50 bg-background/80 backdrop-blur-sm md:hidden">
          <div className="fixed inset-y-0 right-0 z-50 h-full w-full border-l bg-background p-6 shadow-lg sm:max-w-sm">
             <div className="flex items-center justify-between mb-6">
               <h3 className="text-lg font-semibold">購物車 ({cartCount})</h3>
               <Button variant="ghost" size="icon" onClick={() => setShowMobileCart(false)}>
                 <X className="h-4 w-4" />
               </Button>
             </div>
             <div className="flex flex-col h-[calc(100%-4rem)]">
                <div className="flex-1 overflow-y-auto -mr-2 pr-2">
                  {cartItems.map(item => (
                    <div key={item.id} className="flex gap-4 mb-4 border-b pb-4">
                       <div className="h-16 w-16 bg-muted rounded flex items-center justify-center bg-gray-100">
                          
                       </div>
                       <div className="flex-1">
                          <h4 className="font-medium line-clamp-1">{item.productName || item.product?.name}</h4>
                          <p className="text-sm text-muted-foreground"></p>
                          <div className="flex items-center gap-2 mt-2">
                             <Button variant="outline" size="icon" className="h-6 w-6" onClick={() => updateCartItemQuantity(item.id, item.quantity - 1)}>-</Button>
                             <span className="text-sm w-4 text-center">{item.quantity}</span>
                             <Button variant="outline" size="icon" className="h-6 w-6" onClick={() => updateCartItemQuantity(item.id, item.quantity + 1)}>+</Button>
                          </div>
                       </div>
                    </div>
                  ))}
                  {cartItems.length === 0 && <p className="text-center text-muted-foreground py-10">購物車是空的</p>}
                </div>
                <div className="mt-4 pt-4 border-t space-y-4">
                  <div className="flex justify-between font-medium">
                    <span>總計</span>
                    <span></span>
                  </div>
                  <Button className="w-full" onClick={() => { setShowMobileCart(false); goToCheckout(); }} disabled={cartItems.length===0}>結帳</Button>
                  <Button variant="outline" className="w-full" onClick={() => setOpenClearCartDialog(true)} disabled={cartItems.length===0}>清空</Button>
                </div>
             </div>
          </div>
        </div>
      )}

      {/* Clear Cart Dialog */}
      <Dialog open={openClearCartDialog} onOpenChange={setOpenClearCartDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>清空購物車</DialogTitle>
            <DialogDescription>
              確定要清空購物車內的所有商品嗎？此操作無法復原。
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setOpenClearCartDialog(false)}>
              取消
            </Button>
            <Button variant="destructive" onClick={clearCart}>
              確定清空
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

export default Shop;

// frontend/src/pages/Shop.vue
<template>
  <v-container fluid class="pa-4">
    <v-row>
      <!-- 側邊篩選欄（桌面版） -->
      <v-col cols="12" md="3" lg="2" class="d-none d-md-block">
        <v-card elevation="0" variant="outlined" class="sticky-top">
          <v-card-title class="text-subtitle-1">篩選</v-card-title>
          <v-card-text>
            <v-text-field
              v-model="searchTerm"
              label="搜尋商品"
              prepend-inner-icon="mdi-magnify"
              variant="outlined"
              density="compact"
              clearable
              class="mb-3"
            />
            <v-select
              v-model="selectedCategory"
              :items="categoryItems"
              label="分類"
              variant="outlined"
              density="compact"
            />
          </v-card-text>

          <!-- 購物車摘要 -->
          <v-divider />
          <v-card-title class="text-subtitle-1 d-flex align-center">
            <v-icon size="small" class="mr-1">mdi-cart</v-icon>
            購物車
            <v-spacer />
            <v-chip size="small" color="primary">{{ cartItems.length }}</v-chip>
          </v-card-title>
          <v-card-text class="pa-2">
            <template v-if="cartItems.length > 0">
              <v-list density="compact" class="overflow-y-auto" style="max-height: 280px">
                <v-list-item
                  v-for="item in cartItems"
                  :key="item.id"
                  class="px-0"
                >
                  <template v-slot:title>
                    <span class="text-body-2">{{ item.productName || item.product?.name }}</span>
                  </template>
                  <template v-slot:subtitle>
                    <span class="text-caption">x {{ item.quantity }}</span>
                  </template>
                  <template v-slot:append>
                    <div class="d-flex align-center ga-1">
                      <v-btn icon size="x-small" variant="text" @click="updateCartItemQuantity(item.id, item.quantity - 1)">
                        <v-icon size="12">mdi-minus</v-icon>
                      </v-btn>
                      <span class="text-caption">{{ item.quantity }}</span>
                      <v-btn icon size="x-small" variant="text" @click="updateCartItemQuantity(item.id, item.quantity + 1)">
                        <v-icon size="12">mdi-plus</v-icon>
                      </v-btn>
                      <v-btn icon size="x-small" variant="text" color="error" @click="removeFromCart(item.id)">
                        <v-icon size="12">mdi-delete</v-icon>
                      </v-btn>
                    </div>
                  </template>
                </v-list-item>
              </v-list>
              <v-btn color="primary" block size="small" class="mt-2" @click="goToCheckout">結帳</v-btn>
              <v-btn color="error" variant="outlined" block size="small" class="mt-1" @click="clearCartDialog = true">清空</v-btn>
            </template>
            <div v-else class="text-center text-body-2 text-medium-emphasis py-4">
              購物車是空的
            </div>
          </v-card-text>
        </v-card>
      </v-col>

      <!-- 商品列表 -->
      <v-col cols="12" md="9" lg="10">
        <!-- 手機版篩選按鈕 -->
        <div class="d-flex d-md-none gap-2 mb-4">
          <v-btn variant="outlined" prepend-icon="mdi-filter" @click="filterDialog = true" block>
            篩選與搜尋
          </v-btn>
          <v-btn variant="outlined" prepend-icon="mdi-cart" @click="cartDrawer = true">
            <v-badge :content="cartItems.length" color="error" :model-value="cartItems.length > 0">
              購物車
            </v-badge>
          </v-btn>
        </div>

        <!-- 載入中 -->
        <div v-if="loading" class="d-flex justify-center py-12">
          <v-progress-circular indeterminate color="primary" size="48" />
        </div>

        <!-- 商品網格 -->
        <v-row v-else>
          <v-col v-if="filteredProducts.length === 0" cols="12" class="text-center py-12">
            <v-icon size="64" color="grey">mdi-package-variant-remove</v-icon>
            <p class="text-body-1 text-medium-emphasis mt-2">沒有找到符合的商品</p>
          </v-col>

          <v-col
            v-for="product in filteredProducts"
            :key="product.id"
            cols="12" sm="6" lg="4"
          >
            <v-card height="100%" class="d-flex flex-column">
              <!-- 商品圖片 -->
              <div class="position-relative bg-grey-lighten-4" style="aspect-ratio: 1">
                <v-img
                  v-if="product.imageUrl"
                  :src="product.imageUrl"
                  :alt="product.name"
                  cover
                  height="100%"
                />
                <div v-else class="d-flex align-center justify-center fill-height">
                  <v-icon size="64" color="grey">mdi-image-off</v-icon>
                </div>
                <!-- 缺貨遮罩 -->
                <div
                  v-if="product.stock === 0"
                  class="position-absolute inset-0 d-flex align-center justify-center bg-black-50"
                  style="background: rgba(0,0,0,0.5)"
                >
                  <v-chip color="grey" size="large">缺貨</v-chip>
                </div>
              </div>

              <v-card-title class="text-body-1 pb-1">
                <span class="text-truncate d-block">{{ product.name }}</span>
              </v-card-title>
              <v-card-subtitle v-if="product.category">
                <v-chip size="x-small" variant="outlined">{{ product.category }}</v-chip>
              </v-card-subtitle>

              <v-card-text class="flex-grow-1 py-2">
                <p class="text-body-2 text-medium-emphasis line-clamp-2">{{ product.description }}</p>
                <div class="d-flex align-center justify-space-between mt-3">
                  <span class="text-h6 font-weight-bold text-primary">
                    ${{ parseFloat(product.price || 0).toFixed(0) }}
                  </span>
                  <span class="text-caption text-medium-emphasis">庫存: {{ product.stock }}</span>
                </div>
              </v-card-text>

              <v-card-actions class="pa-3 pt-0">
                <v-btn
                  color="primary"
                  variant="flat"
                  class="flex-grow-1"
                  :disabled="product.stock === 0"
                  @click="addToCart(product.id)"
                  prepend-icon="mdi-cart-plus"
                >
                  {{ product.stock === 0 ? '缺貨' : '加入購物車' }}
                </v-btn>
                <v-btn
                  icon
                  variant="outlined"
                  size="small"
                  @click="toggleWishlist(product.id)"
                >
                  <v-icon :color="wishlistedIds.has(product.id) ? 'red' : 'grey'">
                    {{ wishlistedIds.has(product.id) ? 'mdi-heart' : 'mdi-heart-outline' }}
                  </v-icon>
                </v-btn>
              </v-card-actions>
            </v-card>
          </v-col>
        </v-row>
      </v-col>
    </v-row>

    <!-- 手機版篩選 Dialog -->
    <v-dialog v-model="filterDialog" max-width="400">
      <v-card>
        <v-card-title>篩選與搜尋</v-card-title>
        <v-card-text>
          <v-text-field
            v-model="searchTerm"
            label="搜尋商品"
            prepend-inner-icon="mdi-magnify"
            variant="outlined"
            clearable
            class="mb-3"
          />
          <v-select
            v-model="selectedCategory"
            :items="categoryItems"
            label="分類"
            variant="outlined"
          />
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn @click="filterDialog = false">確定</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <!-- 手機版購物車 Drawer -->
    <v-navigation-drawer v-model="cartDrawer" location="right" temporary width="300">
      <v-list-item title="購物車" nav>
        <template v-slot:append>
          <v-btn icon size="small" @click="cartDrawer = false">
            <v-icon>mdi-close</v-icon>
          </v-btn>
        </template>
      </v-list-item>
      <v-divider />
      <v-list density="compact">
        <v-list-item v-for="item in cartItems" :key="item.id">
          <template v-slot:title>
            <span class="text-body-2">{{ item.productName || item.product?.name }}</span>
          </template>
          <template v-slot:append>
            <div class="d-flex align-center ga-1">
              <v-btn icon size="x-small" variant="text" @click="updateCartItemQuantity(item.id, item.quantity - 1)">
                <v-icon size="12">mdi-minus</v-icon>
              </v-btn>
              <span class="text-caption">{{ item.quantity }}</span>
              <v-btn icon size="x-small" variant="text" @click="updateCartItemQuantity(item.id, item.quantity + 1)">
                <v-icon size="12">mdi-plus</v-icon>
              </v-btn>
            </div>
          </template>
        </v-list-item>
      </v-list>
      <template v-slot:append>
        <div class="pa-3">
          <v-btn color="primary" block @click="goToCheckout" :disabled="cartItems.length === 0">結帳</v-btn>
        </div>
      </template>
    </v-navigation-drawer>

    <!-- 清空購物車確認 -->
    <v-dialog v-model="clearCartDialog" max-width="360">
      <v-card>
        <v-card-title>清空購物車</v-card-title>
        <v-card-text>確定要清空購物車內的所有商品嗎？</v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn @click="clearCartDialog = false">取消</v-btn>
          <v-btn color="error" @click="clearCart">清空</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </v-container>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { useRouter } from 'vue-router'
import { useToast } from 'vue-toastification'
import { productAPI, cartAPI, chatAPI, wishlistAPI } from '../services/api.js'
import { useAuthStore } from '../stores/authStore.js'
import { cartEvents } from '../utils/cartEvents.js'

const router = useRouter()
const toast = useToast()
const authStore = useAuthStore()
const user = computed(() => authStore.user)

const products = ref([])
const cartItems = ref([])
const loading = ref(true)
const searchTerm = ref('')
const selectedCategory = ref('all')
const categories = ref([])
const wishlistedIds = ref(new Set())
const filterDialog = ref(false)
const cartDrawer = ref(false)
const clearCartDialog = ref(false)

let interval = null

const categoryItems = computed(() => [
  { title: '全部分類', value: 'all' },
  ...categories.value.map(c => ({ title: c, value: c })),
])

const filteredProducts = computed(() => {
  return products.value.filter(p => {
    const matchSearch = !searchTerm.value ||
      p.name?.toLowerCase().includes(searchTerm.value.toLowerCase()) ||
      p.description?.toLowerCase().includes(searchTerm.value.toLowerCase())
    const matchCategory = selectedCategory.value === 'all' || p.category === selectedCategory.value
    return matchSearch && matchCategory
  })
})

async function loadProducts() {
  try {
    const response = await productAPI.getProducts()
    const data = response.data?.data || response.data || {}
    const list = Array.isArray(data) ? data : (data.content || [])
    products.value = list
    categories.value = [...new Set(list.map(p => p.category).filter(Boolean))]
    loading.value = false
  } catch {
    products.value = []
    loading.value = false
  }
}

async function loadCartItems() {
  if (!user.value?.id) return
  try {
    const response = await cartAPI.getCart(user.value.id)
    const cartData = response.data?.data || response.data
    cartItems.value = cartData?.items || []
  } catch {}
}

async function addToCart(productId) {
  if (!user.value?.id) { toast.error('請先登入'); return }
  try {
    await cartAPI.addToCart(user.value.id, { productId, quantity: 1 })
    await loadCartItems()
    cartEvents.notify()
    toast.success('已加入購物車')
  } catch (err) {
    toast.error(err.response?.data?.error || '加入購物車失敗')
  }
}

async function updateCartItemQuantity(itemId, quantity) {
  if (!user.value?.id) return
  if (quantity < 1) { await removeFromCart(itemId); return }
  try {
    await cartAPI.updateCartItem(user.value.id, itemId, quantity)
    await loadCartItems()
    cartEvents.notify()
  } catch (err) {
    toast.error(err.response?.data?.error || '更新失敗')
  }
}

async function removeFromCart(itemId) {
  if (!user.value?.id) return
  try {
    await cartAPI.removeFromCart(user.value.id, itemId)
    await loadCartItems()
    cartEvents.notify()
  } catch {}
}

async function clearCart() {
  if (!user.value?.id) return
  clearCartDialog.value = false
  try {
    await cartAPI.clearCart(user.value.id)
    await loadCartItems()
    toast.success('購物車已清空')
  } catch {
    toast.error('清空購物車失敗')
  }
}

async function loadWishlist() {
  if (!user.value?.id) return
  try {
    const response = await wishlistAPI.getWishlist()
    const items = response.data?.items ?? response.data ?? []
    wishlistedIds.value = new Set(items.map(item => item.productId ?? item.product?.id))
  } catch {}
}

async function toggleWishlist(productId) {
  if (!user.value?.id) { toast.error('請先登入'); return }
  try {
    if (wishlistedIds.value.has(productId)) {
      await wishlistAPI.removeFromWishlist(productId)
      wishlistedIds.value = new Set([...wishlistedIds.value].filter(id => id !== productId))
      toast.success('已從願望清單移除')
    } else {
      await wishlistAPI.addToWishlist(productId)
      wishlistedIds.value = new Set([...wishlistedIds.value, productId])
      toast.success('已加入願望清單')
    }
  } catch (err) {
    toast.error(err.response?.data?.message || '操作失敗')
  }
}

function goToCheckout() {
  if (cartItems.value.length === 0) { toast.error('購物車是空的！'); return }
  router.push('/checkout')
}

onMounted(() => {
  loadProducts()
  loadCartItems()
  loadWishlist()
  interval = setInterval(loadCartItems, 10000)
  cartEvents.subscribe(() => loadCartItems())
})

onUnmounted(() => {
  if (interval) clearInterval(interval)
})
</script>
